# This file was generated by GoReleaser. DO NOT EDIT.
cask "kc" do
  version "0.1.5"

  on_macos do
    on_intel do
      sha256 "18bfda0fd8233249cb816a2690049cd3fcb4e2faf4431f99745b013bb3980d28"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ee06ccffb0f51b4fd5e18772ee483ab1e928342052aff8226a0a9c40766d64f9"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2ec50f908beb9ce018db0ced9250abc5f577de243f1566e3516010551e639b1a"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "b575016b46610042c6283a5c3649dc17e9f2dc06bc3ca2bf700b8651c38d6e28"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kc"
  desc "Keyboard-driven, Midnight-Commander-style Kubernetes operations TUI"
  homepage "https://github.com/backhand/kc"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kubernetes-cli",
    ]

  binary "kc"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kc"]
  end

  # No zap stanza required

  caveats <<~EOS
    kc also uses git and gh (GitHub CLI) for the deploy flow.
  EOS
end
