# This file was generated by GoReleaser. DO NOT EDIT.
cask "kc" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "cd2e0437f60c63fc73a10ca279e634d3960fa2f9898ac023d532971e92a2ecca"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "9bcf249859e0c6897aa6a50384db4499d18aada59e82a88a876df4055a876874"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e706c118a352b6475e8560f95aecf1f11395acdbfc6d9d1e702d61ea76d812a2"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6af033ebde55feedd4a94495d5834f5b38c5b7880fdf2f92ba58dabfb37e5522"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kc"
  desc "Keyboard-driven, Midnight-Commander-style Kubernetes operations TUI"
  homepage "https://github.com/backhand/kc"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kubernetes-cli",
    ]

  binary "kc"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kc"]
  end

  # No zap stanza required

  caveats <<~EOS
    kc also uses git and gh (GitHub CLI) for the deploy flow.
  EOS
end
