# This file was generated by GoReleaser. DO NOT EDIT.
cask "kc" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "ac3efb21ea3b0cdff0440179da82bbe0ef2b48b32ad536c4f3f7631d70bede58"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f1b4c9db04fe000d35fce214493bc6421018beac5e99f7483da0b087f918d29"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "efb8f61f3281a50bc6333801a7de41f8b443c3c767c1dcd9a3d5c1d81938c219"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9136fa0b338f22cb49ba0dab09ffb02666113a32ac6edb161944123bdbe972f2"
      url "https://github.com/backhand/kc/releases/download/v#{version}/kc_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kc"
  desc "Keyboard-driven, Midnight-Commander-style Kubernetes operations TUI"
  homepage "https://github.com/backhand/kc"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "kubernetes-cli",
    ]

  binary "kc"

  postflight do
    system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kc"]
  end

  # No zap stanza required

  caveats <<~EOS
    kc also uses git and gh (GitHub CLI) for the deploy flow.
  EOS
end
